export const contents: string[] = [
  '1 set of chef knives, professional grade',
  'Organic honey jars x20, wildflower',
  'Custom wedding cake, 3-tier, vanilla',
  'Handcrafted wooden chess set, oak',
  'Limited edition sneakers, size 9 x10',
  'Vintage vinyl records, 60s-70s, x15',
  'Personalized silver cufflinks, x25 pairs',
  'Eco-friendly yoga mats x15, assorted colors',
  'Children’s books, illustrated, x30',
  'High-performance laptops x5, latest model',
  'GoPro cameras x10, adventure pack',
  'Professional art supplies, full set',
  'Exotic fruits assortment, 50kg',
  'Rare comic books collection, x20',
  'Premium coffee beans, 100kg mix',
  'Handmade scented candles x50, variety',
  'Outdoor camping gear set for 10',
  'Luxury skincare bundle, 25 items',
  'Signed sports memorabilia, x10 pieces',
  'Organic cotton bedding sets x15, queen',
  'Books collection, 50 pcs, various genres',
  'Electronics: phones, headphones, 20 items',
  'Furniture: flat-pack table for living room',
  'Clothing: 100 t-shirts, multiple colors',
  'Food parcel: snacks, drinks, non-perishable',
  'Home appliances: microwave, coffee machine',
  'Sports equipment: 2 bicycles, helmets',
  'Car parts: tires, filters, and brake pads',
  'Beauty products: skincare and makeup, 150 pcs',
  'Stationery: pens, notebooks, 200 items',
  'Toys: lego sets, dolls, 50 pcs',
  'Pet supplies: food, toys, bedding, 30 items',
  'Art supplies: paints, brushes, canvases',
  'Office furniture: chairs, desks, 5 pcs',
  'Gardening tools: spades, gloves, 15 items',
  'Musical instruments: guitar, keyboard',
  'Construction materials: tiles, 50 sq meters',
  'Pharmaceuticals: medications, vitamins',
  'Organic produce: fruits, vegetables, 100 kg',
  'Fresh flowers: roses, tulips, 200 stems',
  'Handcrafted leather wallets, 20 pcs',
  'Vintage tea set, porcelain, 15 pcs',
  'Luxury silk scarves, assorted colors, 30 pcs',
  'Organic essential oils set, 10 bottles',
  'Antique pocket watches, 5 pcs',
  'Designer handbags, various styles, 10 pcs',
  'Gourmet chocolate assortment, 50 pcs',
  'High-end headphones, noise-cancelling, 5 pcs',
  'Limited edition board games, 10 pcs',
  'Premium wine selection, 20 bottles',
  'Artisanal cheese assortment, 30 kg',
  'Handmade soap set, organic, 50 pcs',
  'Fitness equipment: yoga mats, weights, 10 pcs',
  'Gourmet pasta selection, 50 kg',
  'Designer sunglasses, various styles, 20 pcs',
  'Luxury watch collection, 5 pcs',
  'High-quality DSLR cameras, 5 pcs',
  'Designer perfume set, 10 bottles',
  'Luxury skincare set, 20 items',
  'Premium tea selection, 30 types',
  'Handmade pottery set, 15 pcs',
  'Gourmet spice assortment, 50 jars',
  'Designer jewelry set, 10 pcs',
  'High-end kitchen appliances, 5 pcs',
  'Luxury bedding set, king size, 10 pcs',
  'Premium coffee machine, 5 pcs',
  'Handcrafted wooden furniture, 5 pcs',
  'Designer lamp collection, 10 pcs',
  'High-quality sound system, 5 pcs',
  'Luxury bathrobe set, 20 pcs'
];
